// Program Data
export const FETCH_PORTFOLIO_NAME_TO_SHOW = "FETCH_PORTFOLIO_NAME_TO_SHOW";
export const UPDATE_PORTFOLIO_NAME_TO_SHOW = "UPDATE_PORTFOLIO_NAME_TO_SHOW";
export const FETCH_TOPUPSTYLE = "FETCH_TOPUPSTYLE"; // FROM CURRENT BROKER

// User Data
export const FETCH_BROKERS = "FETCH_BROKERS";
export const ADD_TO_BROKERS = "ADD_TO_BROKERS";
export const FETCH_LOGS = "FETCH_LOGS";
export const ADD_TO_LOGS = "ADD_TO_LOGS";