// Program Data
export const FETCH_PORTFOLIO_NAME_TO_SHOW = "FETCH_PORTFOLIO_NAME_TO_SHOW";
export const UPDATE_PORTFOLIO_NAME_TO_SHOW = "UPDATE_PORTFOLIO_NAME_TO_SHOW";

// User Data
export const FETCH_BROKERS = "FETCH_BROKERS";
export const ADD_TO_BROKERS = "ADD_TO_BROKERS";
export const FETCH_LOGS = "FETCH_LOGS";
export const ADD_TO_LOGS = "ADD_TO_LOGS";